import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const generateVoterGuide = (userData, candidates, booth) => {
  const doc = new jsPDF();
  const saffron = [255, 153, 51];
  const navy = [0, 0, 128];

  // Header
  doc.setFillColor(...navy);
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Smart Election Assistant', 105, 20, { align: 'center' });
  doc.setFontSize(12);
  doc.text('Personalized Voter Guide & Report Card', 105, 30, { align: 'center' });

  // User Profile
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text('Voter Profile', 15, 55);
  doc.setLineWidth(0.5);
  doc.setDrawColor(...saffron);
  doc.line(15, 57, 50, 57);

  const profileData = [
    ['Name', userData?.name || 'N/A'],
    ['State', userData?.state || 'N/A'],
    ['Constituency', userData?.constituency || 'N/A'],
    ['Voter ID', userData?.voterIdNumber ? 'Verified' : 'Pending']
  ];

  doc.autoTable({
    startY: 65,
    head: [],
    body: profileData,
    theme: 'plain',
    styles: { fontSize: 11, cellPadding: 2 },
    columnStyles: { 0: { fontStyle: 'bold', width: 40 } }
  });

  // Polling Booth
  const currentY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(16);
  doc.text('Your Polling Booth', 15, currentY);
  doc.line(15, currentY + 2, 65, currentY + 2);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(booth?.name || 'Government Primary School, Sector 4', 15, currentY + 10);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(booth?.address || 'Plot 45, Near Community Center, New Delhi', 15, currentY + 16);

  // Candidate Shortlist
  const candidateY = currentY + 30;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text('Candidate Shortlist', 15, candidateY);
  doc.line(15, candidateY + 2, 65, candidateY + 2);

  const candidateData = candidates.map(c => [c.name, c.party, c.constituency]);
  doc.autoTable({
    startY: candidateY + 10,
    head: [['Name', 'Party', 'Constituency']],
    body: candidateData.length > 0 ? candidateData : [['Candidate A', 'Party X', 'Constituency 1']],
    headStyles: { fillColor: navy },
    styles: { fontSize: 10 }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`Generated by Smart Election Assistant on ${new Date().toLocaleDateString()}`, 105, 285, { align: 'center' });
  }

  doc.save('My_Voter_Guide.pdf');
};
